export const OPEN_LATERAL_NAV = "OPEN_LATERAL_NAV";
export const CLOSE_LATERAL_NAV = "CLOSE_LATERAL_NAV";
// shops new
export const SHOP_NEW_FORM_OPEN = "SHOP_NEW_FORM_OPEN";
export const SHOP_NEW_FORM_CLOSE = "SHOP_NEW_FORM_CLOSE";
export const SHOP_SUCCESS_CREATE = "SHOP_SUCCESS_CREATE";
// shops edit
export const SHOP_EDIT_FORM_OPEN = "SHOP_EDIT_FORM_OPEN";
export const SHOP_EDIT_FORM_CLOSE = "SHOP_EDIT_FORM_CLOSE";
export const SHOP_SUCCESS_EDIT = "SHOP_SUCCESS_EDIT";