export const FETCH_SIGN_IN = "FETCH_LOGIN";
export const SUCCESS_SIGN_IN = "SUCCESS_LOGIN";
export const ERROR_SIGN_IN = "ERROR_LOGIN";
export const RESET_SIGN_IN_ERRORS = "RESET_SIGN_IN_ERRORS";
export const VALIDATE_SIGN_IN_TOKEN = "VALIDATE_SIGN_IN_TOKEN";
export const ERROR_SIGN_IN_TOKEN = "ERROR_SIGN_IN_TOKEN";
export const FETCH_SIGN_OUT = "FETCH_SIGN_OUT";
export const SUCCESS_SIGN_OUT = "SUCCESS_SIGN_OUT";