// SIGN IN TYPES
export const FETCH_SIGN_IN = "FETCH_LOGIN";
export const SUCCESS_SIGN_IN = "SUCCESS_LOGIN";
export const ERROR_SIGN_IN = "ERROR_LOGIN";
export const RESET_SIGN_IN_ERRORS = "RESET_SIGN_IN_ERRORS";
// SIGN UP TYPES
export const FETCH_SIGN_UP = "FETCH_SIGN_UP";
export const SUCCESS_SIGN_UP = "SUCCESS_SIGN_UP";
export const ERROR_SIGN_UP = "ERROR_SIGN_UP";
export const RESET_ERROR_SIGN_UP = "RESET_ERROR_SIGN_UP";
// TOKEN VALIDATE TYPES
export const VALIDATE_SIGN_IN_TOKEN = "VALIDATE_SIGN_IN_TOKEN";
export const ERROR_SIGN_IN_TOKEN = "ERROR_SIGN_IN_TOKEN";
// SIGN OUT TYPES
export const FETCH_SIGN_OUT = "FETCH_SIGN_OUT";
export const SUCCESS_SIGN_OUT = "SUCCESS_SIGN_OUT";